import { StyleSheet } from 'react-native';
import { colors, layout, radius, shadows, spacing, typography } from '@/design-system';

export const AppleColors = {
  systemBlue: colors.primary,
  systemGreen: colors.success,
  systemIndigo: '#4F46E5',
  systemOrange: colors.warning,
  systemPink: '#0FBAAF',
  systemPurple: '#8B5CF6',
  systemRed: colors.danger,
  systemTeal: '#14B8A6',
  systemYellow: '#EAB308',
  systemGray: '#94A3B8',
  systemGray2: '#A8B3C6',
  systemGray3: '#CBD5E1',
  systemGray4: '#E2E8F0',
  systemGray5: '#F1F5F9',
  systemGray6: '#F8FAFC',
  label: colors.textPrimary,
  secondaryLabel: colors.textMuted,
  tertiaryLabel: colors.textMuted,
  quaternaryLabel: colors.textMuted,
  systemBackground: colors.background,
  secondarySystemBackground: colors.surface,
  tertiarySystemBackground: colors.surface,
  systemGroupedBackground: colors.background,
  secondarySystemGroupedBackground: colors.surface,
  tertiarySystemGroupedBackground: colors.background,
  systemFill: '#64748B33',
  secondarySystemFill: '#64748B22',
  tertiarySystemFill: '#64748B18',
  quaternarySystemFill: '#64748B12',
  separator: colors.border,
  opaqueSeparator: colors.border,
};

export const AppleTypography = {
  sfProDisplay: 'SF-Pro-Display-Regular',
  sfProDisplayMedium: 'SF-Pro-Display-Medium',
  sfProDisplaySemibold: 'SF-Pro-Display-Semibold',
  sfProDisplayBold: 'SF-Pro-Display-Bold',
  largeTitle: 32,
  title1: 28,
  title2: 22,
  title3: 20,
  headline: 18,
  body: 15,
  callout: 15,
  subhead: 14,
  footnote: 13,
  caption1: 12,
  caption2: 12,
};

export const AppleSpacing = spacing;

export const AppleBorderRadius = {
  small: radius.sm,
  medium: radius.md,
  large: radius.lg,
  xlarge: radius.xl,
  continuous: radius.xl,
};

export const AppleShadows = {
  small: shadows.sm,
  medium: shadows.md,
  large: shadows.md,
};

export const GlobalStyles = StyleSheet.create({
  largeTitle: { ...typography.h1 },
  title1: { ...typography.h1 },
  title2: { ...typography.h2 },
  title3: { ...typography.h2 },
  headline: { ...typography.h2 },
  body: { ...typography.body },
  callout: { ...typography.body },
  subhead: { ...typography.body, color: colors.textMuted },
  footnote: { ...typography.caption },
  caption1: { ...typography.caption },
  caption2: { ...typography.caption },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    minHeight: layout.buttonHeight,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButton: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    minHeight: layout.buttonHeight,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardLarge: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: colors.border,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  textInput: {
    minHeight: layout.buttonHeight,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    fontSize: 15,
    lineHeight: 22,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.border,
  },
  listItem: {
    backgroundColor: colors.surface,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  navigationBar: {
    backgroundColor: colors.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
});
