import { Platform, TextStyle, ViewStyle } from 'react-native';
import { createShadow } from '@/src/utils/shadows';

export const iosFonts = {
  regular: Platform.select({ ios: 'System', android: 'sans-serif', web: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif', default: 'System' }),
  medium: Platform.select({ ios: 'System', android: 'sans-serif-medium', web: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif', default: 'System' }),
  semibold: Platform.select({ ios: 'System', android: 'sans-serif-medium', web: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif', default: 'System' }),
  bold: Platform.select({ ios: 'System', android: 'sans-serif', web: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif', default: 'System' }),
  extrabold: Platform.select({ ios: 'System', android: 'sans-serif', web: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif', default: 'System' }),
  black: Platform.select({ ios: 'System', android: 'sans-serif', web: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif', default: 'System' }),
} as const;

/** Apple HIG palette — refined for premium Millennial appeal */
export const premiumPalette = {
  background: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceSoft: '#F8F9FA',
  surfaceGlass: 'rgba(255,255,255,0.85)',
  textPrimary: '#1C1C1E',
  textSecondary: '#6E6E73',
  iconInactive: '#8E8E93',
  border: 'rgba(60,60,67,0.12)',
  divider: 'rgba(60,60,67,0.18)',
  systemBlue: '#6A11CB',
  systemGreen: '#34C759',
  systemOrange: '#FF9500',
  systemRed: '#FF3B30',
  systemPurple: '#A020F0', // added purple for guest UI
  accent: '#6A11CB',
  accentDark: '#4A0080',
  accentSoft: 'rgba(106,17,203,0.1)',
  // Enhanced colors for better depth and sophistication
  elevated: '#FFFFFF',
  backgroundElevated: '#F8F9FA',
  separator: 'rgba(60,60,67,0.29)',
  label: '#6E6E73',
  link: '#6A11CB',
  charcoal: '#1C1C1E',
} as const;

export const iosPalette = {
  light: {
    background: premiumPalette.background,
    surface: premiumPalette.surface,
    surfaceElevated: premiumPalette.surfaceSoft,
    surfaceSoft: premiumPalette.surfaceSoft,
    surfaceTertiary: '#EFEFF4',
    surfaceGlass: premiumPalette.surfaceGlass,
    primary: premiumPalette.accent,
    primaryDark: premiumPalette.accentDark,
    primarySoft: premiumPalette.accentSoft,
    textPrimary: premiumPalette.textPrimary,
    textSecondary: premiumPalette.textSecondary,
    textTertiary: 'rgba(60,60,67,0.30)',
    border: premiumPalette.border,
    separator: premiumPalette.divider,
    iconInactive: premiumPalette.iconInactive,
    charcoal: premiumPalette.charcoal,
    systemBlue: premiumPalette.systemBlue,
    systemGreen: premiumPalette.systemGreen,
    systemOrange: premiumPalette.systemOrange,
    systemPurple: premiumPalette.systemPurple,
    label: premiumPalette.label,
    link: premiumPalette.link,
    // Enhanced elevations for depth
    elevation1: 'rgba(0,0,0,0.05)',
    elevation2: 'rgba(0,0,0,0.08)',
    elevation3: 'rgba(0,0,0,0.11)',
    elevation4: 'rgba(0,0,0,0.14)',
  },
  dark: {
    background: '#0A0C12',
    surface: '#1C1C1E',
    surfaceElevated: '#2C2C2E',
    surfaceSoft: '#2C2C2E',
    surfaceTertiary: '#3A3A3C',
    surfaceGlass: 'rgba(28,28,30,0.92)',
    primary: premiumPalette.accent,
    primaryDark: '#5FE38D',
    primarySoft: 'rgba(48,209,88,0.18)',
    textPrimary: '#FFFFFF',
    textSecondary: 'rgba(235,235,245,0.60)',
    textTertiary: 'rgba(235,235,245,0.30)',
    border: 'rgba(84,84,88,0.65)',
    separator: 'rgba(84,84,88,0.65)',
    iconInactive: '#8E8E93',
    charcoal: '#FFFFFF',
    systemBlue: '#0A84FF',
    systemGreen: '#30D158',
    systemOrange: '#FF9F0A',
    systemPurple: '#BF5AF2',
    label: '#8E8E93',
    link: '#0A84FF',
    // Enhanced elevations for dark mode
    elevation1: 'rgba(255,255,255,0.05)',
    elevation2: 'rgba(255,255,255,0.08)',
    elevation3: 'rgba(255,255,255,0.11)',
    elevation4: 'rgba(255,255,255,0.14)',
  },
} as const;

export const iosTypography = {
  display: {
    fontSize: 34,
    lineHeight: 40,
    fontFamily: iosFonts.black,
    fontWeight: '900' as const,
    letterSpacing: -0.5,
  } satisfies TextStyle,
  h1: {
    fontSize: 28,
    lineHeight: 34,
    fontFamily: iosFonts.extrabold,
    fontWeight: '800' as const,
    letterSpacing: -0.3,
  } satisfies TextStyle,
  h2: {
    fontSize: 22,
    lineHeight: 28,
    fontFamily: iosFonts.bold,
    fontWeight: '700' as const,
    letterSpacing: -0.2,
  } satisfies TextStyle,
  h3: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: iosFonts.semibold,
    fontWeight: '600' as const,
    letterSpacing: -0.1,
  } satisfies TextStyle,
  h4: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: iosFonts.medium,
    fontWeight: '500' as const,
    letterSpacing: 0,
  } satisfies TextStyle,
  body: {
    fontSize: 17,
    lineHeight: 24,
    fontFamily: iosFonts.regular,
    fontWeight: '400' as const,
    letterSpacing: -0.2,
  } satisfies TextStyle,
  bodySmall: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: iosFonts.regular,
    fontWeight: '400' as const,
    letterSpacing: -0.1,
  } satisfies TextStyle,
  callout: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: iosFonts.regular,
    fontWeight: '400' as const,
    letterSpacing: -0.2,
  } satisfies TextStyle,
  caption: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: iosFonts.medium,
    fontWeight: '500' as any,
    letterSpacing: 0,
  } satisfies TextStyle,
  caption2: {
    fontSize: 11,
    lineHeight: 15,
    fontFamily: iosFonts.medium,
    fontWeight: '500' as any,
    letterSpacing: 0,
  } satisfies TextStyle,
  footnote: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: iosFonts.regular,
    fontWeight: '400' as const,
    letterSpacing: -0.1,
  } satisfies TextStyle,
  subhead: {
    fontSize: 15,
    lineHeight: 20,
    fontFamily: iosFonts.medium,
    fontWeight: '500' as const,
    letterSpacing: -0.1,
  } satisfies TextStyle,
  headline: {
    fontSize: 17,
    lineHeight: 22,
    fontFamily: iosFonts.semibold,
    fontWeight: '600' as const,
    letterSpacing: -0.2,
  } satisfies TextStyle,
  title1: {
    fontSize: 24,
    lineHeight: 30,
    fontFamily: iosFonts.bold,
    fontWeight: '700' as const,
    letterSpacing: -0.5,
  } satisfies TextStyle,
  title2: {
    fontSize: 20,
    lineHeight: 26,
    fontFamily: iosFonts.bold,
    fontWeight: '700' as const,
    letterSpacing: -0.5,
  } satisfies TextStyle,
  title3: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: iosFonts.bold,
    fontWeight: '700' as const,
    letterSpacing: -0.5,
  } satisfies TextStyle,
} as const;

export const iosDesign = {
  spacing: {
    xxxs: 2,
    xxs: 4,
    xs: 6,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    xxl: 28,
    xxxl: 32,
    event: 36,
    paragraph: 40,
    section: 48,
    content: 56,
    sidebar: 64,
    gutter: 8,
    gutter2: 16,
    comfort: 18,
  },
  radius: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 20,
    pill: 999,
    // More nuanced radius values for sophistication
    subtle: 4,
    moderate: 8,
    significant: 12,
    prominent: 16,
    dramatic: 20,
    hero: 24,
  },
  iconSize: {
    xxxs: 12,
    xxs: 14,
    xs: 16,
    sm: 18,
    md: 20,
    lg: 22,
    xl: 24,
    xxl: 26,
    tab: 28,
    lg2: 32,
    hero: 36,
    feature: 40,
    marketing: 48,
    tiny: 10,
  },
  avatarSize: {
    xs: 24,
    sm: 28,
    md: 32,
    lg: 36,
    xl: 40,
    xxl: 48,
    chat: 48,
    profile: 56,
    largeProfile: 80,
    hero: 96,
    banner: 120,
    logo: 120,
  },
  controlHeight: {
    xs: 28,
    sm: 32,
    md: 36,
    lg: 40,
    xl: 44,
    xxl: 48,
    xxxl: 48,
    search: 44,
    input: 44,
    hero: 52,
    default: 44,
  },
  hitTarget: 44,
  shadows: {
    // More sophisticated shadow system
    none: { shadowColor: 'transparent', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0, shadowRadius: 0, elevation: 0 },
    subtle: createShadow({ color: '#000000', offset: { width: 0, height: 1 }, opacity: 0.05, radius: 2, elevation: 1 }),
    low: createShadow({ color: '#000000', offset: { width: 0, height: 2 }, opacity: 0.08, radius: 4, elevation: 2 }),
    medium: createShadow({ color: '#000000', offset: { width: 0, height: 4 }, opacity: 0.12, radius: 8, elevation: 3 }),
    high: createShadow({ color: '#000000', offset: { width: 0, height: 6 }, opacity: 0.16, radius: 12, elevation: 4 }),
    // Elevated shadows for cards and elevated surfaces
    card: createShadow({ color: '#000000', offset: { width: 0, height: 4 }, opacity: 0.08, radius: 12, elevation: 3 }),
    elevated: createShadow({ color: '#000000', offset: { width: 0, height: 6 }, opacity: 0.12, radius: 16, elevation: 4 }),
    floating: createShadow({ color: '#000000', offset: { width: 0, height: 8 }, opacity: 0.16, radius: 20, elevation: 6 }),
    dialog: createShadow({ color: '#000000', offset: { width: 0, height: 10 }, opacity: 0.2, radius: 24, elevation: 8 }),
    control: createShadow({ color: '#000000', offset: { width: 0, height: 2 }, opacity: 0.07, radius: 4, elevation: 2 }), // added control shadow
  } satisfies Record<string, ViewStyle>,
  animation: {
    // More refined animation curves and timing
    spring: { damping: 20, stiffness: 150 },
    quick: { duration: 120 },
    normal: { duration: 180 },
    slow: { duration: 240 },
    linger: { duration: 300 },
    // More precise timing curves
    easeInOut: 'cubic-bezier(0.42, 0, 0.58, 1)',
    easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
    easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
    linear: 'linear',
    // Spring configurations for different use cases
    springGentle: { damping: 15, stiffness: 120 },
    springDefault: { damping: 20, stiffness: 150 },
    springBold: { damping: 25, stiffness: 180 },
    // Press scales
    softPressScale: 0.95,
  },
} as const;

export const rolePalettes = {
  default: {
    primary: premiumPalette.accent,
    primaryDark: premiumPalette.accentDark,
    soft: premiumPalette.accentSoft,
    surfaceTint: 'rgba(0,0,0,0.05)',
  },
  sales: {
    primary: premiumPalette.systemBlue,
    primaryDark: premiumPalette.accentDark,
    soft: premiumPalette.accentSoft,
    surfaceTint: 'rgba(0,122,255,0.05)',
  },
  printer: {
    primary: premiumPalette.systemOrange,
    primaryDark: '#D35400',
    soft: 'rgba(255,149,0,0.1)',
    surfaceTint: 'rgba(255,149,0,0.05)',
  },
  admin: {
    primary: premiumPalette.systemRed,
    primaryDark: '#D32F2F',
    soft: 'rgba(255,59,48,0.1)',
    surfaceTint: 'rgba(255,59,48,0.05)',
  },
  // Enhanced role palettes with more sophistication
  system: {
    primary: premiumPalette.systemBlue,
    primaryDark: '#0051D5',
    soft: 'rgba(0,122,255,0.1)',
    surfaceTint: 'rgba(0,0,0,0.05)',
  },
  gaming: {
    primary: '#FF2D55',
    primaryDark: '#E6004A',
    soft: 'rgba(255,45,85,0.1)',
    surfaceTint: 'rgba(255,45,85,0.05)',
  },
  productivity: {
    primary: '#34C759',
    primaryDark: '#28A745',
    soft: 'rgba(52,199,89,0.1)',
    surfaceTint: 'rgba(52,199,89,0.05)',
  },
  creativity: {
    primary: '#FF9500',
    primaryDark: '#D35400',
    soft: 'rgba(255,149,0,0.1)',
    surfaceTint: 'rgba(255,149,0,0.05)',
  },
  finance: {
    primary: '#007AFF',
    primaryDark: '#0051D5',
    soft: 'rgba(0,122,255,0.1)',
    surfaceTint: 'rgba(0,122,255,0.05)',
  },
  health: {
    primary: '#34C759',
    primaryDark: '#28A745',
    soft: 'rgba(52,199,89,0.1)',
    surfaceTint: 'rgba(52,199,89,0.05)',
  },
  travel: {
    primary: '#FF3B30',
    primaryDark: '#D32F2F',
    soft: 'rgba(255,59,48,0.1)',
    surfaceTint: 'rgba(255,59,48,0.05)',
  },
  food: {
    primary: '#FF9500',
    primaryDark: '#D35400',
    soft: 'rgba(255,149,0,0.1)',
    surfaceTint: 'rgba(255,149,0,0.05)',
  },
  social: {
    primary: '#FF2D55',
    primaryDark: '#E6004A',
    soft: 'rgba(255,45,85,0.1)',
    surfaceTint: 'rgba(255,45,85,0.05)',
  },
  education: {
    primary: '#5AC8FA',
    primaryDark: '#007AFF',
    soft: 'rgba(90,200,250,0.1)',
    surfaceTint: 'rgba(90,200,250,0.05)',
  },
} as const;