import { Platform, TextStyle, ViewStyle } from 'react-native';

export const iosFonts = {
  regular: Platform.select({ ios: 'Inter_400Regular', web: 'Inter_400Regular, -apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif', default: 'Inter_400Regular' }),
  medium: Platform.select({ ios: 'Inter_500Medium', web: 'Inter_500Medium, -apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif', default: 'Inter_500Medium' }),
  semibold: Platform.select({ ios: 'Inter_600SemiBold', web: 'Inter_600SemiBold, -apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif', default: 'Inter_600SemiBold' }),
  bold: Platform.select({ ios: 'Inter_700Bold', web: 'Inter_700Bold, -apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif', default: 'Inter_700Bold' }),
  extrabold: Platform.select({ ios: 'Inter_800ExtraBold', web: 'Inter_800ExtraBold, -apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif', default: 'Inter_800ExtraBold' }),
  black: Platform.select({ ios: 'Inter_900Black', web: 'Inter_900Black, -apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif', default: 'Inter_900Black' }),
} as const;

/** Apple HIG palette — neutral-first, semantic color for meaning only */
export const premiumPalette = {
  background: '#F2F2F7',
  surface: '#FFFFFF',
  surfaceSoft: '#F9F9FB',
  surfaceGlass: 'rgba(255,255,255,0.86)',
  textPrimary: '#000000',
  textSecondary: '#6E6E73',
  iconInactive: '#8E8E93',
  border: 'rgba(60,60,67,0.12)',
  divider: 'rgba(60,60,67,0.18)',
  systemBlue: '#007AFF',
  systemGreen: '#34C759',
  systemOrange: '#FF9500',
  systemRed: '#FF3B30',
  accent: '#007AFF',
  accentDark: '#0051D5',
  accentSoft: 'rgba(0,122,255,0.12)',
  charcoal: '#000000',
  charcoalSoft: 'rgba(0,0,0,0.05)',
} as const;

export const iosPalette = {
  light: {
    background: premiumPalette.background,
    surface: premiumPalette.surface,
    surfaceElevated: premiumPalette.surfaceSoft,
    surfaceSoft: premiumPalette.surfaceSoft,
    surfaceTertiary: '#EFEFF4',
    surfaceGlass: premiumPalette.surfaceGlass,
    primary: premiumPalette.accent,
    primaryDark: premiumPalette.accentDark,
    primarySoft: premiumPalette.accentSoft,
    textPrimary: premiumPalette.textPrimary,
    textSecondary: premiumPalette.textSecondary,
    textTertiary: 'rgba(60,60,67,0.30)',
    border: premiumPalette.border,
    separator: premiumPalette.divider,
    iconInactive: premiumPalette.iconInactive,
    charcoal: premiumPalette.charcoal,
    systemBlue: premiumPalette.systemBlue,
  },
  dark: {
    background: '#0A0C12',
    surface: '#1C1C1E',
    surfaceElevated: '#2C2C2E',
    surfaceSoft: '#2C2C2E',
    surfaceTertiary: '#3A3A3C',
    surfaceGlass: 'rgba(28,28,30,0.92)',
    primary: premiumPalette.accent,
    primaryDark: '#5FE38D',
    primarySoft: 'rgba(48,209,88,0.18)',
    textPrimary: '#FFFFFF',
    textSecondary: 'rgba(235,235,245,0.60)',
    textTertiary: 'rgba(235,235,245,0.30)',
    border: 'rgba(84,84,88,0.65)',
    separator: 'rgba(84,84,88,0.65)',
    iconInactive: '#8E8E93',
    charcoal: '#FFFFFF',
    systemBlue: '#0A84FF',
  },
} as const;

export const iosTypography = {
  display: {
    fontSize: 40,
    lineHeight: 46,
    fontFamily: iosFonts.black,
    fontWeight: '900',
    letterSpacing: 0,
  } satisfies TextStyle,
  h1: {
    fontSize: 32,
    lineHeight: 38,
    fontFamily: iosFonts.extrabold,
    fontWeight: '800',
    letterSpacing: 0,
  } satisfies TextStyle,
  h2: {
    fontSize: 22,
    lineHeight: 28,
    fontFamily: iosFonts.bold,
    fontWeight: '700',
    letterSpacing: 0,
  } satisfies TextStyle,
  body: {
    fontSize: 17,
    lineHeight: 24,
    fontFamily: iosFonts.regular,
    fontWeight: '400',
    letterSpacing: 0,
  } satisfies TextStyle,
  bodySmall: {
    fontSize: 15,
    lineHeight: 21,
    fontFamily: iosFonts.regular,
    fontWeight: '400',
    letterSpacing: 0,
  } satisfies TextStyle,
  caption: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: iosFonts.medium,
    fontWeight: '500',
    letterSpacing: 0,
  } satisfies TextStyle,
  metric: {
    fontSize: 34,
    lineHeight: 40,
    fontFamily: iosFonts.black,
    fontWeight: '900',
    letterSpacing: 0,
  } satisfies TextStyle,
} as const;

export const iosDesign = {
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    comfort: 20,
    lg: 24,
    xl: 32,
    premium: 40,
    xxl: 48,
    hero: 64,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    hero: 24,
    pill: 999,
  },
  iconSize: {
    tiny: 16,
    sm: 20,
    md: 24,
    tab: 28,
    lg: 32,
    hero: 40,
    feature: 48,
    marketing: 64,
  },
  avatarSize: {
    sm: 32,
    md: 40,
    chat: 48,
    profile: 80,
    largeProfile: 120,
    logo: 150,
  },
  controlHeight: {
    sm: 36,
    default: 44,
    primary: 52,
    hero: 56,
    search: 44,
    input: 52,
  },
  hitTarget: 44,
  shadows: {
    card: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: Platform.select({ ios: 0.07, android: 0.08, default: 0.06 }),
      shadowRadius: 14,
      elevation: 1,
    } satisfies ViewStyle,
    floating: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: Platform.select({ ios: 0.12, android: 0.12, default: 0.1 }),
      shadowRadius: 22,
      elevation: 2,
    } satisfies ViewStyle,
    control: {
      shadowColor: '#1C1C1E',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: Platform.select({ ios: 0.03, android: 0.04, default: 0.03 }),
      shadowRadius: 4,
      elevation: 0,
    } satisfies ViewStyle,
  },
  animation: {
    pressScale: 0.98,
    softPressScale: 0.99,
    duration: {
      fast: 160,
      base: 240,
      slow: 360,
    },
  },
} as const;

export const rolePalettes = {
  default: {
    primary: premiumPalette.accent,
    primaryDark: premiumPalette.accentDark,
    soft: premiumPalette.accentSoft,
    surfaceTint: premiumPalette.charcoalSoft,
  },
  sales: {
    primary: '#F4C20D',
    primaryDark: '#B88A00',
    soft: 'rgba(244,194,13,0.12)',
    surfaceTint: 'rgba(244,194,13,0.06)',
  },
  printer: {
    primary: premiumPalette.accent,
    primaryDark: premiumPalette.accentDark,
    soft: premiumPalette.accentSoft,
    surfaceTint: premiumPalette.charcoalSoft,
  },
  admin: {
    primary: premiumPalette.accent,
    primaryDark: premiumPalette.accentDark,
    soft: premiumPalette.accentSoft,
    surfaceTint: premiumPalette.charcoalSoft,
  },
} as const;
