export const appRoutes = {
  login: '/auth/login',
  register: '/auth/register',
  customerTabs: '/(tabs)',
  accountOrders: '/account/orders',
  customerConnections: '/(tabs)/connections',
  customerAnalysis: '/(tabs)/profile',
  customerSettings: '/(tabs)/settings',
  customerShare: '/(tabs)/share',
  /** @deprecated Use customerConnections — kept for cached guest routes */
  customerConnectionsLegacy: '/(tabs)/attendance',
  scan: '/scan',
  nfcDemo: '/nfc-demo',
  qrGenerator: '/qr-generator',
  studio: '/studio',
  guestAnalytics: '/guest-analytics',
  guestDesign: '/guest-design',
  guestCardPreview: '/card-preview/[cardId]',
  /** @deprecated Deep links only — redirects to guestDesign */
  guestChooseCard: '/guest-choose-card',
  guestCheckout: '/guest-checkout',
  guestCardCheckout: '/checkout/[cardId]',
  guestTrackOrder: '/guest-track-order',
  guestPostLoginChoice: '/guest-post-login-choice',
  newOrder: '/new-order',
  orderDetail: '/order-detail/[orderId]',
  editBio: '/edit-bio',
  themePicker: '/theme-picker',
  customer: {
    root: '/customer',
    orders: '/customer/orders',
    templates: '/customer/templates',
    profile: '/customer/profile',
    notifications: '/customer/notifications',
  },
  sales: {
    root: '/sales',
    orders: '/sales/orders',
    newOrder: '/sales/new-order',
    payouts: '/sales/payouts',
    notifications: '/sales/notifications',
    settings: '/sales/settings',
    customers: '/sales/customers',
    me: '/sales/me',
  },
} as const;
