export const appRoutes = {
  login: '/auth/login',
  register: '/auth/register',
  customerTabs: '/(tabs)',
  accountOrders: '/account/orders',
  customerConnections: '/(tabs)/connections',
  /** @deprecated Use customerConnections — kept for cached guest routes */
  customerConnectionsLegacy: '/(tabs)/attendance',
  scan: '/scan',
  nfcDemo: '/nfc-demo',
  guestAnalytics: '/guest-analytics',
  guestDesign: '/guest-design',
  guestCardPreview: '/card-preview/[cardId]',
  /** @deprecated Deep links only — redirects to guestDesign */
  guestChooseCard: '/guest-choose-card',
  guestCheckout: '/guest-checkout',
  guestCardCheckout: '/checkout/[cardId]',
  guestTrackOrder: '/guest-track-order',
  guestPostLoginChoice: '/guest-post-login-choice',
  newOrder: '/new-order',
  orderDetail: '/order-detail/[orderId]',
  sales: {
    root: '/sales',
    orders: '/sales/orders',
    newOrder: '/sales/new-order',
    payouts: '/sales/payouts',
    notifications: '/sales/notifications',
    settings: '/sales/settings',
  },
  printer: {
    batchSelect: '/printer/batch-select',
    queue: '/printer/queue',
    newOrder: '/printer/new-order',
    settings: '/printer/settings',
    wages: '/printer/wages',
    notifications: '/printer/notifications',
  },
  qa: { root: '/qa' },
  shipping: { root: '/shipping' },
} as const;
